apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection-svc
  name: connection-svc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: connection-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection-svc
  name: connection-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection-svc
  template:
    metadata:
      labels:
        service: connection-svc
    spec:
      containers:
      - image: 0906784480/connection-service:latest
        name: connection-svc-container
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-connections-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_PORT
        - name: PERSON_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: PERSON_SERVICE_URL
      restartPolicy: Always
